# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('vegetarian', models.CharField(choices=[('Veg', 'Vegetarian'), ('Non-Veg', 'Non Vegetarian')], max_length=7)),
                ('photo_1', models.CharField(max_length=200)),
                ('photo_2', models.CharField(max_length=200)),
                ('photo_3', models.CharField(max_length=200)),
                ('photo_4', models.CharField(max_length=200)),
                ('photo_5', models.CharField(max_length=200)),
                ('cuisine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='www.Cuisine')),
            ],
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('photo_1', models.CharField(max_length=200)),
                ('photo_2', models.CharField(max_length=200)),
                ('photo_3', models.CharField(max_length=200)),
                ('photo_4', models.CharField(max_length=200)),
                ('photo_5', models.CharField(max_length=200)),
                ('last_updated', models.DateTimeField(verbose_name='Capture Date and Time of last update to Restaurant')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='www.Area')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='foodCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='www.FoodCategory'),
        ),
        migrations.AddField(
            model_name='food',
            name='kitchen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='www.Kitchen'),
        ),
    ]
