# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_auto_20161104_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
