# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0003_auto_20161104_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
