# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0005_food_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodaySpecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='www.Food')),
            ],
        ),
    ]
