# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0006_todayspecial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todayspecial',
            name='kitchen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='www.Kitchen'),
        ),
    ]
